#!/usr/bin/env python3

from src import algorithms as algs
from src import utils

def main():
    try:
        utils.errorHandler()
        utils.csvHandler()
    except (RuntimeError, ValueError) as e:
        print("Error: " + str(e))
        exit(84)
    except BaseException as e:
        print(e)
        exit (0)
    algs.ganttAlgorithm()
    exit(0)

main()